-- Add profile fields to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_picture VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS hourly_rate DECIMAL(10,2);
ALTER TABLE users ADD COLUMN IF NOT EXISTS skills TEXT[];
ALTER TABLE users ADD COLUMN IF NOT EXISTS languages JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS availability VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS experience_level VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS education JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS certifications JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS portfolio JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS testimonials JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS employment_history JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS other_experiences JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS verifications JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS licenses JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS company_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS company_description TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS company_website VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS company_size VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS industry VARCHAR(100);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_location ON users(location);
CREATE INDEX IF NOT EXISTS idx_users_skills ON users USING GIN(skills);
CREATE INDEX IF NOT EXISTS idx_users_hourly_rate ON users(hourly_rate);
